# Generated by Django 4.2.10 on 2024-02-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntreeappbackend', '0001_initial'),
    ]

    operations = [
        
    ]
