# Generated by Django 4.2.10 on 2024-02-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntreeappbackend', '0002_auto_20240211_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.IntegerField(),
        ),
    ]
